# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-30 04:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course_app', '0002_enrolled'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enrolled',
            old_name='student',
            new_name='user',
        ),
    ]
