# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-30 04:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course_app', '0003_auto_20161129_2025'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='enrolled',
            options={'managed': False},
        ),
    ]
