# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-30 07:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course_app', '0005_auto_20161129_2050'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={},
        ),
        migrations.AlterModelOptions(
            name='enrolled',
            options={},
        ),
    ]
