# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-30 03:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_reg', '0002_auto_20161128_2134'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='course',
        ),
    ]
